language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
notifications:
  slack:
    secure: NrCS5dFtZr+79pKrdtrPWQn19hyfG0TIeUwO+6B9g4loU0R3bg2/BQPvJBcP06Q99vGbzpABNZUIiezVXixfFlmMbhFx16ZEPfW05ZMcv4HAjYTKaoBtxqVLAKK51YQSAOo9thKK+YpNU907bsY1U9LCPH9irfdt3uIApoTM0eeZBuRmZjgJC9WmTmEdWxJ0nZf+xZx8kx0xdFsWHQD7k+FCtf7R5eY2UhZPOdhzID7aT4SI21/BZi7u9UizapORsceGBb7XC8Rxt1SiAu4+K+rdax2XXbjTfzSoh8bJpRaR99B0T/ol5+I0GXD6WgltL/jSWu8l1rVcbFEaGawrp+GAHwF/emTafuycpGvNGKZpZtUI2Tag9wZuPxwccIlGrmATiVmOv7dh2na3va1nojMWfrt1RENXVHnayTHF1eZFkHgQKYJN9S1NqBY/duj+FJngHA4krwk+KGcBfWWTh7UAe0FFrZdzSPz8IqZZPNffpMRalH/7Ccz8J35EOfRVUAFWDbEL9Amo28DVluBHtGZ40BhpIYULa9LpbyhoTVfPBCuDCz2GWQc3uEpIHcHaKuk2l29sO0RH9Mu0izvUAzZmkb9lqs942JDnOGNGw2PhwuOZ94lGVpH2QczfCtaC1sjiWBIm/CZWuXHT9py7/LYATp/GZSU0S6NE+NSiNb4=
