name: IceBall
main: com.crystalcraftmc.iceball.main.Snowball
version: 0.4
description: IceBall is a Spigot plugin that allows you to have snowball fights with other players in ways you never expected!
authors: [Jwood9198, jflory7]
website: http://crystalcraftmc.com

commands:
   createSnowball:
      description: Specify 2 corners in which to place your snowball arena
      usage: /<command> <x1> <y1> <z1> <x2> <y2> <z2>
   deleteSnowball:
      description: Remove the current snowball arena if any
      usage: /<command>
   showSnowball:
      description: Show the 2 corner coordinates of the current snowball
      usage: /<command>
   snowballPerms:
      description: No-args shows list of ppl with perms; you can also add/remove people from list
      usage: /<command> <add_remove> <player name>
   snowballMaintenance:
      description: No-args teleports to the edge of snowball arena; or specify 3 args for maitenance location
      usage: /<command> <x> <y> <z>
   snowballClearLimit:
      description:
         Shrink the border of the arena for which inventories get cleared upon a tp.
      usage:
         /<command> <limit-amount>
